title: Mi Hogar
description: Vétraz-Monthoux
baseurl: "/hogar-view"
url: "https://edurobrus.github.io"
markdown: kramdown

collections_dir: data
collections:
  tareas:
    output: true
    permalink: /tareas/:name/
  eventos:
    output: true
    permalink: /eventos/:name/
  recetas:
    output: true
    permalink: /recetas/:name/
  limpieza:
    output: true
    permalink: /limpieza/:name/
  hoteles:
    output: true
    permalink: /hoteles/:name/
  restaurantes:
    output: true
    permalink: /restaurantes/:name/
  frances:
    output: true
    permalink: /frances/:name/

defaults:
  - scope:
      path: ""
      type: tareas
    values:
      layout: item
  - scope:
      path: ""
      type: eventos
    values:
      layout: item
  - scope:
      path: ""
      type: recetas
    values:
      layout: item
  - scope:
      path: ""
      type: limpieza
    values:
      layout: item
  - scope:
      path: ""
      type: hoteles
    values:
      layout: item
  - scope:
      path: ""
      type: restaurantes
    values:
      layout: item
  - scope:
      path: ""
      type: frances
    values:
      layout: item
